#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DEFAULT_SERVICE_ROOT="$HOME/.openclaw/mira-light-service"
DEFAULT_WORKSPACE_RUNTIME_DIR="$HOME/.openclaw/workspace/runtime"

ROOT_DIR="${MIRA_LIGHT_SERVICE_ROOT:-$DEFAULT_SERVICE_ROOT}"
if [[ ! -d "${ROOT_DIR}/scripts" && -d "${REPO_ROOT}/scripts" ]]; then
  ROOT_DIR="${REPO_ROOT}"
fi

if [[ -n "${MIRA_LIGHT_WORKSPACE_RUNTIME_DIR:-}" ]]; then
  WORKSPACE_RUNTIME_DIR="${MIRA_LIGHT_WORKSPACE_RUNTIME_DIR}"
elif [[ "${ROOT_DIR}" == "${REPO_ROOT}" ]]; then
  WORKSPACE_RUNTIME_DIR="${REPO_ROOT}/runtime/live-vision"
else
  WORKSPACE_RUNTIME_DIR="${DEFAULT_WORKSPACE_RUNTIME_DIR}"
fi

VISION_HOST="${MIRA_LIGHT_VISION_HOST:-0.0.0.0}"
VISION_PORT="${MIRA_LIGHT_VISION_PORT:-8000}"
BASE_URL="${MIRA_LIGHT_BASE_URL:-tcp://192.168.31.10:9527}"
POLL_INTERVAL="${MIRA_LIGHT_VISION_POLL_INTERVAL:-0.5}"
TRACKING_UPDATE_MS="${MIRA_LIGHT_TRACKING_UPDATE_MS:-220}"
TABLETOP_TRACKING_UPDATE_MS="${MIRA_LIGHT_TABLETOP_TRACKING_UPDATE_MS:-160}"
TOUCH_PERSISTENCE_FRAMES="${MIRA_LIGHT_TOUCH_PERSISTENCE_FRAMES:-3}"
TOUCH_COOLDOWN_MS="${MIRA_LIGHT_TOUCH_COOLDOWN_MS:-9000}"
TOUCH_MIN_CONFIDENCE="${MIRA_LIGHT_TOUCH_MIN_CONFIDENCE:-0.72}"
TOUCH_MIN_SIZE_NORM="${MIRA_LIGHT_TOUCH_MIN_SIZE_NORM:-0.085}"
TOUCH_MAX_CENTER_OFFSET="${MIRA_LIGHT_TOUCH_MAX_CENTER_OFFSET:-0.32}"
TOUCH_HAND_ARM_MIN_CONFIDENCE="${MIRA_LIGHT_TOUCH_HAND_ARM_MIN_CONFIDENCE:-0.68}"
HAND_AVOID_COOLDOWN_MS="${MIRA_LIGHT_HAND_AVOID_COOLDOWN_MS:-7000}"
HAND_AVOID_MIN_CONFIDENCE="${MIRA_LIGHT_HAND_AVOID_MIN_CONFIDENCE:-0.78}"
HAND_AVOID_MAX_CENTER_Y="${MIRA_LIGHT_HAND_AVOID_MAX_CENTER_Y:-0.74}"
HAND_AVOID_EXTENDED_MAX_CENTER_Y="${MIRA_LIGHT_HAND_AVOID_EXTENDED_MAX_CENTER_Y:-0.86}"
HAND_AVOID_EXTENDED_MIN_CONFIDENCE="${MIRA_LIGHT_HAND_AVOID_EXTENDED_MIN_CONFIDENCE:-0.90}"
HAND_AVOID_MIN_LATERAL_OFFSET="${MIRA_LIGHT_HAND_AVOID_MIN_LATERAL_OFFSET:-0.18}"
SCENE_ALLOWED_DETECTORS="${MIRA_LIGHT_SCENE_ALLOWED_DETECTORS:-haar_face,hog_person,tabletop_object,book_cover_color}"
TRACKING_ALLOWED_DETECTORS="${MIRA_LIGHT_TRACKING_ALLOWED_DETECTORS:-haar_face,hog_person,background_motion,tabletop_object,book_cover_color}"
TOUCH_ALLOWED_DETECTORS="${MIRA_LIGHT_TOUCH_ALLOWED_DETECTORS:-haar_face,hog_person}"
LOG_LEVEL="${MIRA_LIGHT_VISION_LOG_LEVEL:-INFO}"
FACE_NEAR_AREA_RATIO="${MIRA_LIGHT_FACE_NEAR_AREA_RATIO:-0.10}"
FACE_MID_AREA_RATIO="${MIRA_LIGHT_FACE_MID_AREA_RATIO:-0.03}"
MOTION_NEAR_AREA_RATIO="${MIRA_LIGHT_MOTION_NEAR_AREA_RATIO:-0.18}"
MOTION_MID_AREA_RATIO="${MIRA_LIGHT_MOTION_MID_AREA_RATIO:-0.06}"
MIN_MOTION_AREA_RATIO="${MIRA_LIGHT_MIN_MOTION_AREA_RATIO:-0.015}"
WARMUP_FRAMES="${MIRA_LIGHT_WARMUP_FRAMES:-5}"
CAPTURE_MAX_SAVED_FRAMES="${MIRA_LIGHT_CAPTURE_MAX_SAVED_FRAMES:-1000}"
HAND_CUE_MIN_AREA_RATIO="${MIRA_LIGHT_HAND_CUE_MIN_AREA_RATIO:-0.0015}"
HAND_CUE_MAX_AREA_RATIO="${MIRA_LIGHT_HAND_CUE_MAX_AREA_RATIO:-0.06}"
HAND_CUE_MIN_CENTER_Y="${MIRA_LIGHT_HAND_CUE_MIN_CENTER_Y:-0.34}"
HAND_CUE_MIN_MOTION_RATIO="${MIRA_LIGHT_HAND_CUE_MIN_MOTION_RATIO:-0.12}"
HAND_CUE_MIN_CONFIDENCE="${MIRA_LIGHT_HAND_CUE_MIN_CONFIDENCE:-0.55}"
SELECTED_TARGET_MAX_CENTER_DISTANCE="${MIRA_LIGHT_SELECTED_TARGET_MAX_CENTER_DISTANCE:-0.16}"
SELECTED_TARGET_MAX_SIZE_DELTA="${MIRA_LIGHT_SELECTED_TARGET_MAX_SIZE_DELTA:-0.045}"
SELECTED_TARGET_SWITCH_MARGIN="${MIRA_LIGHT_SELECTED_TARGET_SWITCH_MARGIN:-0.22}"
DEFAULT_TARGET_MODE="${MIRA_LIGHT_DEFAULT_TARGET_MODE:-person_follow}"
TABLETOP_ROI_TOP="${MIRA_LIGHT_TABLETOP_ROI_TOP:-0.16}"
TABLETOP_ROI_BOTTOM="${MIRA_LIGHT_TABLETOP_ROI_BOTTOM:-0.96}"
TABLETOP_ROI_LEFT="${MIRA_LIGHT_TABLETOP_ROI_LEFT:-0.08}"
TABLETOP_ROI_RIGHT="${MIRA_LIGHT_TABLETOP_ROI_RIGHT:-0.92}"
TABLETOP_MIN_AREA_RATIO="${MIRA_LIGHT_TABLETOP_MIN_AREA_RATIO:-0.004}"
TABLETOP_MAX_AREA_RATIO="${MIRA_LIGHT_TABLETOP_MAX_AREA_RATIO:-0.65}"
TABLETOP_MIN_EDGE_RATIO="${MIRA_LIGHT_TABLETOP_MIN_EDGE_RATIO:-0.05}"
TABLETOP_MIN_MOTION_RATIO="${MIRA_LIGHT_TABLETOP_MIN_MOTION_RATIO:-0.01}"
TABLETOP_MIN_ASPECT_RATIO="${MIRA_LIGHT_TABLETOP_MIN_ASPECT_RATIO:-0.45}"
TABLETOP_MAX_ASPECT_RATIO="${MIRA_LIGHT_TABLETOP_MAX_ASPECT_RATIO:-2.2}"
TABLETOP_HOLD_MISSING_FRAMES="${MIRA_LIGHT_TABLETOP_HOLD_MISSING_FRAMES:-6}"
TABLETOP_SWITCH_MARGIN="${MIRA_LIGHT_TABLETOP_SWITCH_MARGIN:-0.34}"
TABLETOP_MAX_CENTER_DISTANCE="${MIRA_LIGHT_TABLETOP_MAX_CENTER_DISTANCE:-0.22}"
TABLETOP_MAX_SIZE_DELTA="${MIRA_LIGHT_TABLETOP_MAX_SIZE_DELTA:-0.065}"
TABLETOP_MAX_ASPECT_DELTA="${MIRA_LIGHT_TABLETOP_MAX_ASPECT_DELTA:-0.48}"
TABLETOP_BOOK_COLOR_ENABLED="${MIRA_LIGHT_TABLETOP_BOOK_COLOR_ENABLED:-1}"
TABLETOP_BOOK_HUE_MIN="${MIRA_LIGHT_TABLETOP_BOOK_HUE_MIN:-14}"
TABLETOP_BOOK_HUE_MAX="${MIRA_LIGHT_TABLETOP_BOOK_HUE_MAX:-43}"
TABLETOP_BOOK_MIN_SATURATION="${MIRA_LIGHT_TABLETOP_BOOK_MIN_SATURATION:-70}"
TABLETOP_BOOK_MIN_VALUE="${MIRA_LIGHT_TABLETOP_BOOK_MIN_VALUE:-80}"
TABLETOP_BOOK_MIN_COLOR_RATIO="${MIRA_LIGHT_TABLETOP_BOOK_MIN_COLOR_RATIO:-0.22}"
TABLETOP_BOOK_MIN_ASPECT_RATIO="${MIRA_LIGHT_TABLETOP_BOOK_MIN_ASPECT_RATIO:-0.35}"
TABLETOP_BOOK_MAX_ASPECT_RATIO="${MIRA_LIGHT_TABLETOP_BOOK_MAX_ASPECT_RATIO:-4.2}"
TABLETOP_BOOK_MIN_RECTANGULARITY="${MIRA_LIGHT_TABLETOP_BOOK_MIN_RECTANGULARITY:-0.46}"
TABLETOP_BOOK_MIN_SOLIDITY="${MIRA_LIGHT_TABLETOP_BOOK_MIN_SOLIDITY:-0.72}"
TABLETOP_BOOK_MIN_EDGE_RATIO="${MIRA_LIGHT_TABLETOP_BOOK_MIN_EDGE_RATIO:-0.012}"
TABLETOP_BOOK_MAX_EDGE_RATIO="${MIRA_LIGHT_TABLETOP_BOOK_MAX_EDGE_RATIO:-0.24}"
TABLETOP_BOOK_MIN_INNER_EDGE_RATIO="${MIRA_LIGHT_TABLETOP_BOOK_MIN_INNER_EDGE_RATIO:-0.012}"
TABLETOP_BOOK_MAX_CORNER_COUNT="${MIRA_LIGHT_TABLETOP_BOOK_MAX_CORNER_COUNT:-6}"
TABLETOP_BOOK_SELECTION_BONUS="${MIRA_LIGHT_TABLETOP_BOOK_SELECTION_BONUS:-0.42}"
OWNER_FACE_REGISTRY="${MIRA_LIGHT_OWNER_FACE_REGISTRY:-}"
OWNER_MATCH_THRESHOLD="${MIRA_LIGHT_OWNER_MATCH_THRESHOLD:-0.82}"
OWNER_SELECTION_BONUS="${MIRA_LIGHT_OWNER_SELECTION_BONUS:-0.24}"
SKIP_RECEIVER="${MIRA_LIGHT_SKIP_RECEIVER:-0}"
ENABLE_CAPTURE_MEMORY_OBSERVER="${MIRA_LIGHT_ENABLE_CAPTURE_MEMORY_OBSERVER:-0}"
CAPTURE_MEMORY_OBSERVER_INTERVAL_SECONDS="${MIRA_LIGHT_CAPTURE_MEMORY_OBSERVER_INTERVAL_SECONDS:-300}"
CAPTURE_MEMORY_OBSERVER_RUNTIME_DIR="${MIRA_LIGHT_CAPTURE_MEMORY_OBSERVER_RUNTIME_DIR:-$WORKSPACE_RUNTIME_DIR/capture-memory-observer}"
CAPTURE_MEMORY_OBSERVER_DRY_RUN="${MIRA_LIGHT_CAPTURE_MEMORY_OBSERVER_DRY_RUN:-0}"

if [[ -n "${MIRA_LIGHT_VISION_PYTHON:-}" ]]; then
  PYTHON_BIN="${MIRA_LIGHT_VISION_PYTHON}"
elif [[ -x "${ROOT_DIR}/.venv/bin/python" ]]; then
  PYTHON_BIN="${ROOT_DIR}/.venv/bin/python"
elif [[ -x "${REPO_ROOT}/.venv/bin/python" ]]; then
  PYTHON_BIN="${REPO_ROOT}/.venv/bin/python"
else
  PYTHON_BIN="$(command -v python3)"
fi

CAPTURES_DIR="${MIRA_LIGHT_CAPTURES_DIR:-$WORKSPACE_RUNTIME_DIR/captures}"
LATEST_EVENT_OUT="${MIRA_LIGHT_LATEST_EVENT_OUT:-$WORKSPACE_RUNTIME_DIR/vision.latest.json}"
EVENTS_JSONL="${MIRA_LIGHT_EVENTS_JSONL:-$WORKSPACE_RUNTIME_DIR/vision.events.jsonl}"
BRIDGE_STATE_OUT="${MIRA_LIGHT_BRIDGE_STATE_OUT:-$WORKSPACE_RUNTIME_DIR/vision.bridge.state.json}"
VISION_OPERATOR_STATE_PATH="${MIRA_LIGHT_VISION_OPERATOR_STATE_PATH:-$WORKSPACE_RUNTIME_DIR/vision.operator.json}"
CAPTURE_MEMORY_LATEST_OBSERVATION_PATH="${MIRA_LIGHT_CAPTURE_MEMORY_LATEST_OBSERVATION_PATH:-$CAPTURE_MEMORY_OBSERVER_RUNTIME_DIR/latest.observation.json}"
CAPTURE_MEMORY_STATUS_PATH="${MIRA_LIGHT_CAPTURE_MEMORY_STATUS_PATH:-$CAPTURE_MEMORY_OBSERVER_RUNTIME_DIR/status.json}"

export MIRA_LIGHT_CAPTURES_DIR="$CAPTURES_DIR"
export MIRA_LIGHT_VISION_EVENT_PATH="$LATEST_EVENT_OUT"
export MIRA_LIGHT_VISION_BRIDGE_STATE_PATH="$BRIDGE_STATE_OUT"
export MIRA_LIGHT_VISION_OPERATOR_STATE_PATH="$VISION_OPERATOR_STATE_PATH"
export MIRA_LIGHT_CAPTURE_MEMORY_LATEST_OBSERVATION_PATH="$CAPTURE_MEMORY_LATEST_OBSERVATION_PATH"
export MIRA_LIGHT_CAPTURE_MEMORY_STATUS_PATH="$CAPTURE_MEMORY_STATUS_PATH"

mkdir -p "$CAPTURES_DIR"
mkdir -p "$(dirname "$LATEST_EVENT_OUT")"
rm -f "$LATEST_EVENT_OUT" "$BRIDGE_STATE_OUT"

if [[ ! -x "$PYTHON_BIN" ]]; then
  echo "Missing Python runtime: $PYTHON_BIN" >&2
  echo "Run: bash scripts/setup_local_mira_light_service_env.sh" >&2
  exit 1
fi

is_truthy() {
  local value="${1:-0}"
  value="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
  case "$value" in
    1|true|yes|on) return 0 ;;
    *) return 1 ;;
  esac
}

RECEIVER_ARGS=(
  --host "$VISION_HOST"
  --port "$VISION_PORT"
  --save-dir "$CAPTURES_DIR"
  --max-saved-frames "$CAPTURE_MAX_SAVED_FRAMES"
  --log-level "$LOG_LEVEL"
)

EXTRACTOR_ARGS=(
  --captures-dir "$CAPTURES_DIR"
  --latest-event-out "$LATEST_EVENT_OUT"
  --events-jsonl "$EVENTS_JSONL"
  --poll-interval "$POLL_INTERVAL"
  --ignore-existing
  --log-level "$LOG_LEVEL"
  --face-near-area-ratio "$FACE_NEAR_AREA_RATIO"
  --face-mid-area-ratio "$FACE_MID_AREA_RATIO"
  --motion-near-area-ratio "$MOTION_NEAR_AREA_RATIO"
  --motion-mid-area-ratio "$MOTION_MID_AREA_RATIO"
  --min-motion-area-ratio "$MIN_MOTION_AREA_RATIO"
  --warmup-frames "$WARMUP_FRAMES"
  --operator-state-file "$VISION_OPERATOR_STATE_PATH"
  --hand-cue-min-area-ratio "$HAND_CUE_MIN_AREA_RATIO"
  --hand-cue-max-area-ratio "$HAND_CUE_MAX_AREA_RATIO"
  --hand-cue-min-center-y "$HAND_CUE_MIN_CENTER_Y"
  --hand-cue-min-motion-ratio "$HAND_CUE_MIN_MOTION_RATIO"
  --hand-cue-min-confidence "$HAND_CUE_MIN_CONFIDENCE"
  --selected-target-max-center-distance "$SELECTED_TARGET_MAX_CENTER_DISTANCE"
  --selected-target-max-size-delta "$SELECTED_TARGET_MAX_SIZE_DELTA"
  --selected-target-switch-margin "$SELECTED_TARGET_SWITCH_MARGIN"
  --default-target-mode "$DEFAULT_TARGET_MODE"
  --tabletop-roi-top "$TABLETOP_ROI_TOP"
  --tabletop-roi-bottom "$TABLETOP_ROI_BOTTOM"
  --tabletop-roi-left "$TABLETOP_ROI_LEFT"
  --tabletop-roi-right "$TABLETOP_ROI_RIGHT"
  --tabletop-min-area-ratio "$TABLETOP_MIN_AREA_RATIO"
  --tabletop-max-area-ratio "$TABLETOP_MAX_AREA_RATIO"
  --tabletop-min-edge-ratio "$TABLETOP_MIN_EDGE_RATIO"
  --tabletop-min-motion-ratio "$TABLETOP_MIN_MOTION_RATIO"
  --tabletop-min-aspect-ratio "$TABLETOP_MIN_ASPECT_RATIO"
  --tabletop-max-aspect-ratio "$TABLETOP_MAX_ASPECT_RATIO"
  --tabletop-hold-missing-frames "$TABLETOP_HOLD_MISSING_FRAMES"
  --tabletop-switch-margin "$TABLETOP_SWITCH_MARGIN"
  --tabletop-max-center-distance "$TABLETOP_MAX_CENTER_DISTANCE"
  --tabletop-max-size-delta "$TABLETOP_MAX_SIZE_DELTA"
  --tabletop-max-aspect-delta "$TABLETOP_MAX_ASPECT_DELTA"
  --tabletop-book-hue-min "$TABLETOP_BOOK_HUE_MIN"
  --tabletop-book-hue-max "$TABLETOP_BOOK_HUE_MAX"
  --tabletop-book-min-saturation "$TABLETOP_BOOK_MIN_SATURATION"
  --tabletop-book-min-value "$TABLETOP_BOOK_MIN_VALUE"
  --tabletop-book-min-color-ratio "$TABLETOP_BOOK_MIN_COLOR_RATIO"
  --tabletop-book-min-aspect-ratio "$TABLETOP_BOOK_MIN_ASPECT_RATIO"
  --tabletop-book-max-aspect-ratio "$TABLETOP_BOOK_MAX_ASPECT_RATIO"
  --tabletop-book-min-rectangularity "$TABLETOP_BOOK_MIN_RECTANGULARITY"
  --tabletop-book-min-solidity "$TABLETOP_BOOK_MIN_SOLIDITY"
  --tabletop-book-min-edge-ratio "$TABLETOP_BOOK_MIN_EDGE_RATIO"
  --tabletop-book-max-edge-ratio "$TABLETOP_BOOK_MAX_EDGE_RATIO"
  --tabletop-book-min-inner-edge-ratio "$TABLETOP_BOOK_MIN_INNER_EDGE_RATIO"
  --tabletop-book-max-corner-count "$TABLETOP_BOOK_MAX_CORNER_COUNT"
  --tabletop-book-selection-bonus "$TABLETOP_BOOK_SELECTION_BONUS"
  --owner-match-threshold "$OWNER_MATCH_THRESHOLD"
  --owner-selection-bonus "$OWNER_SELECTION_BONUS"
)

if ! is_truthy "$TABLETOP_BOOK_COLOR_ENABLED"; then
  EXTRACTOR_ARGS+=(--disable-tabletop-book-color)
fi

if [[ -n "$OWNER_FACE_REGISTRY" ]]; then
  EXTRACTOR_ARGS+=(--owner-face-registry "$OWNER_FACE_REGISTRY")
fi

BRIDGE_ARGS=(
  --event-file "$LATEST_EVENT_OUT"
  --bridge-state-out "$BRIDGE_STATE_OUT"
  --poll-interval "$POLL_INTERVAL"
  --tracking-update-ms "$TRACKING_UPDATE_MS"
  --tabletop-tracking-update-ms "$TABLETOP_TRACKING_UPDATE_MS"
  --touch-persistence-frames "$TOUCH_PERSISTENCE_FRAMES"
  --touch-cooldown-ms "$TOUCH_COOLDOWN_MS"
  --touch-min-confidence "$TOUCH_MIN_CONFIDENCE"
  --touch-min-size-norm "$TOUCH_MIN_SIZE_NORM"
  --touch-max-center-offset "$TOUCH_MAX_CENTER_OFFSET"
  --touch-hand-arm-min-confidence "$TOUCH_HAND_ARM_MIN_CONFIDENCE"
  --hand-avoid-cooldown-ms "$HAND_AVOID_COOLDOWN_MS"
  --hand-avoid-min-confidence "$HAND_AVOID_MIN_CONFIDENCE"
  --hand-avoid-max-center-y "$HAND_AVOID_MAX_CENTER_Y"
  --hand-avoid-extended-max-center-y "$HAND_AVOID_EXTENDED_MAX_CENTER_Y"
  --hand-avoid-extended-min-confidence "$HAND_AVOID_EXTENDED_MIN_CONFIDENCE"
  --hand-avoid-min-lateral-offset "$HAND_AVOID_MIN_LATERAL_OFFSET"
  --scene-allowed-detectors "$SCENE_ALLOWED_DETECTORS"
  --tracking-allowed-detectors "$TRACKING_ALLOWED_DETECTORS"
  --touch-allowed-detectors "$TOUCH_ALLOWED_DETECTORS"
  --base-url "$BASE_URL"
)

if is_truthy "${MIRA_LIGHT_ALLOW_EXPERIMENTAL:-0}"; then
  BRIDGE_ARGS+=(--allow-experimental)
fi

if is_truthy "${MIRA_LIGHT_TOUCH_ALLOW_PERSON_FALLBACK:-0}"; then
  BRIDGE_ARGS+=(--touch-allow-person-fallback)
fi

cleanup() {
  local exit_code=$?
  if [[ -n "${RECEIVER_PID:-}" ]]; then kill "$RECEIVER_PID" >/dev/null 2>&1 || true; fi
  if [[ -n "${EXTRACTOR_PID:-}" ]]; then kill "$EXTRACTOR_PID" >/dev/null 2>&1 || true; fi
  if [[ -n "${BRIDGE_PID:-}" ]]; then kill "$BRIDGE_PID" >/dev/null 2>&1 || true; fi
  if [[ -n "${CAPTURE_MEMORY_OBSERVER_PID:-}" ]]; then kill "$CAPTURE_MEMORY_OBSERVER_PID" >/dev/null 2>&1 || true; fi
  wait || true
  exit "$exit_code"
}
trap cleanup EXIT INT TERM

if is_truthy "${MIRA_LIGHT_VISION_DRY_RUN:-0}"; then
  BRIDGE_ARGS+=(--dry-run)
fi

if ! is_truthy "$SKIP_RECEIVER"; then
  "$PYTHON_BIN" "$ROOT_DIR/scripts/cam_receiver_service.py" "${RECEIVER_ARGS[@]}" &
  RECEIVER_PID=$!
fi

"$PYTHON_BIN" "$ROOT_DIR/scripts/track_target_event_extractor.py" "${EXTRACTOR_ARGS[@]}" &
EXTRACTOR_PID=$!

"$PYTHON_BIN" "$ROOT_DIR/scripts/vision_runtime_bridge.py" "${BRIDGE_ARGS[@]}" &
BRIDGE_PID=$!

if is_truthy "$ENABLE_CAPTURE_MEMORY_OBSERVER"; then
  CAPTURE_MEMORY_ARGS=(
    --captures-dir "$CAPTURES_DIR"
    --runtime-dir "$CAPTURE_MEMORY_OBSERVER_RUNTIME_DIR"
    --latest-observation-out "$CAPTURE_MEMORY_LATEST_OBSERVATION_PATH"
    --status-out "$CAPTURE_MEMORY_STATUS_PATH"
    --interval-seconds "$CAPTURE_MEMORY_OBSERVER_INTERVAL_SECONDS"
    --log-level "$LOG_LEVEL"
  )
  if is_truthy "$CAPTURE_MEMORY_OBSERVER_DRY_RUN"; then
    CAPTURE_MEMORY_ARGS+=(--dry-run)
  fi
  "$PYTHON_BIN" "$ROOT_DIR/scripts/capture_memory_observer.py" "${CAPTURE_MEMORY_ARGS[@]}" &
  CAPTURE_MEMORY_OBSERVER_PID=$!
fi

WAIT_PIDS=()
if [[ -n "${RECEIVER_PID:-}" ]]; then
  WAIT_PIDS+=("$RECEIVER_PID")
fi
WAIT_PIDS+=("$EXTRACTOR_PID" "$BRIDGE_PID")
if [[ -n "${CAPTURE_MEMORY_OBSERVER_PID:-}" ]]; then
  WAIT_PIDS+=("$CAPTURE_MEMORY_OBSERVER_PID")
fi

wait "${WAIT_PIDS[@]}"
